### PR TITLE
fix 0.12 branch for ruby 2.4

### PR DESCRIPTION
**Pull request by ehowe**

### CODE REVIEW

**Comment by ehowe** [comment]
For some reason ruby 2.4 breaks inline rescue when you try to add to a nil hash

**Comment by ehowe** [comment]
@lanej any chance you could merge this and cut a new release of 0.12 for me?  the specs seem to have broken in this branch for a long time, so I didn't bother trying to fix them.

**Comment by lanej** [comment]
Simple enough.

**Comment by lanej** [comment]
https://rubygems.org/gems/cistern/versions/0.12.3

**Comment by ehowe** [comment]
YTMND

**Pull request merged**
